### ISSUE TITLE
frontend api

### ISSUE THREAD

**Issue by bkehle** [bkehle/307backend#3]
campaign example - json string of an array of strings -> ["name", "start date", "end date"]

ad example - json string of an array of strings -> ["main text", "sub text", "url"]

**Comment by jyee27** [comment]
Doesn't have to be exactly this format; just make sure it has all the information we need.
If we're storing things with numerical IDs, our GET endpoints should include IDs and our POST endpoints should not (they'll be auto-incremented).
Let us know what the API looks like (endpoints and the data they give/receive) in #frontend or #general on Slack once that's decided.

**Comment by sjfoz1019** [comment]
I would like something more detailed and concrete. See #4
