### ISSUE TITLE
Specification of API

### ISSUE THREAD

**Issue by sjfoz1019** [bkehle/307backend#4]
Can we define an actual spec after the model of [CHSRest](http://ec2-34-221-236-150.us-west-2.compute.amazonaws.com//WebDev/Modules/02HTTPandREST/2CHSREST/CHSREST.html)? I think something clear, detailed, and specific would be extremely helpful for implementation and integration of both the backend and frontend. We need to know the design and how the two ends will interact before we can actually start building with a clear direction.

**Comment by sjfoz1019** [comment]
**Some things to consider:**
- What constitutes an Ad or Campaign object?
    - What is their JSON representation?
- How are relations between Ads and Campaigns stored and sent? 
    - i.e., by ID or by the whole object?
- What are the endpoints for the REST controller? 
    - What HTTP verbs should they accept?
    - What is their format? 
        - i.e., something like [site]/ads/{id} and [site]/campaigns/{id}?
        - Should [site]/campaigns/{id}/ads/{id} be allowed, or should you take the ad's id from the campaign and GET [site]/ads/{id} instead?
            - Or will ads always be accessed through campaigns?
- What actions should those endpoints accomplish?
    - i.e., return a Campaign object in JSON string such and such or create a new Ad object with properties such and such
- What should those endpoints return (and not just on a GET request)? 
    - What should be returned in case of an error?
    - What is the format of objects returned?
- What should the endpoints accept as input?

**Comment by sjfoz1019** [comment]
Started drafting spec in README.md on branch sounds-like-we-should-have-a-spec

**Comment by jyee27** [comment]
Some thoughts:

/campaigns/{id} DELETE
-
> TODO: What happens to the ads?

I think we should delete all connected ads. If we're using a DB we could use `ON DELETE CASCADE` to make things simple, otherwise we can filter the array in memory.

/campaigns/{id}/ads
-
> Are ads always tied to a campaign?
Can one ad be associated with multiple campaigns?

For simplicity let's say that ads are always tied to only one campaign.

/campaigns/{id}/ads POST
-
> (TODO: is campaign really necessary in this setup?)

I think including the campaign ID in ads and storing them separately from campaigns would be simpler than storing them inside campaign objects.

General Points
-
> TODO: How are we storing dates?

Epoch seconds is probably simplest:
https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#getEpochSecond--
Values stored as int.

Alternatively we could use `DateTimeFormatter` and pick one of the predefined formatters there:
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
Values stored as String.

If we use a DB, we can use `java.sql.Timestamp`:
https://docs.oracle.com/javase/8/docs/api/java/sql/Timestamp.html
Values stored in DB as a SQL `datetime` and converted to epoch seconds/String when sending through the API.

**Comment by bkehle** [comment]
### /campaigns
Map of all campaigns. The key is a unique ID and the value is a Campaign object. A Campaign object consists of a String name, int start date, int end date, and a List of Advertisement objects. 

**POST** - adds a new Campaign. HTTP request body contains JSON string of a list of values. Example: [ "id" , "name" , "start date" , "end date"]

**GET** - chooses a random Ad from within a random Campaign and returns this Ad as a JSON string.
                 Example: '{"main text":"some text", "sub text":"some more text", "url":"some url"}'

### /campaigns/{campId}

**DELETE** - deletes Campaign with specific id from map.  Ads within object are also deleted.

### /campaigns/{campId}/ads
Map of all Advertisement objects in a specific campaign. The key is a unique ID and the value is an Advertisement object. An Advertisement object consists of a String main text, String sub text, and String url.

**POST** - adds a new Advertisement to that specific Campaign. HTTP request body contains JSON string of a list of values. Example: '["id","main text","sub text","url"]'

### /campaigns/{campId}/ads/{adId}

**DELETE** - deletes Advertisement with specific id from map.


Notable Changes:
-I think the best way to store Campaigns and Ads are with a Map. The key will be a unique int id.
     -Also, I think it will be easiest to store ads within a campaign so we don't have to have 2 separate Maps for Campaign and 
     Ads 
-Currently how I have it structured, frontend will send a new id with the http request and auto increment for the next post.

Other Notes:
-Still have to figure out which errors to send.

**Comment by sjfoz1019** [comment]
@bkehle 
**Questions:**
- Why would you send ads/campaigns as JSON lists instead of objects?
    - e.g., [id,"blah","something","www.someadurl.xyz"] instead of {"id":id, "mainText":"blah", "subText":"something", "url":"www.someadurl.xyz"}
    - Having the key:value pairs makes more sense to me and would be clearer and easier to parse
- Why is the *frontend* responsible for assigning the ids that are used to identify the objects on the *backend*?
    - I don't think we can assume the frontend has knowledge of the backend structure
        - *We* may not always be the frontend
    - What if the front and back ends get de-synced?
        - Could result in overwriting data or trying to access things that don't exist
            - This is not user-friendly
    - I can't articulate exactly why right now, but it just doesn't make sense

**Suggestions:**
- If you want to manage an ad server, you will likely still want to be able to list all campaigns. Therefore, I suggest keeping GET /campaigns as returning all campaigns and creating a separate endpoint for getting a random ad:
### /random
#### GET
Returns a random ad from any campaign
### /random/{campID}
#### GET
Returns a random ad from campaign with campID

**Comment by sjfoz1019** [comment]
## What needs to **GET** (pun very much intended) done:
- Explicitly define the nebulous categories of "Ad" and "Campaign."
    - What exactly is needed for each? 
    - In the frontend demo, I saw some fields that don't exist in the backend. We're going to need to implement those, right? 
    - Also, prune out what isn't needed for now.
- Explicitly define the vague relationship of Ads and Campaigns.
    - Are ads always tied to a campaign? Can one ad be associated with multiple campaigns? 
    - Bret and John said two different things about storing ads within campaigns vs. storing ads and campaigns separately. Which one are we going with?
    - What happens to ads on deletion of campaign?
- Define how we will send and store dates. 
    - Epoch seconds? A specifically formatted string?
- Write a Postman test suite to ensure correctness of API and enforce the spec.
