### ISSUE TITLE
Frontend: Get ads from server

### ISSUE THREAD

**Issue by jyee27** [bkehle/307backend#50]
As a user, I want to see the ads that are stored on the server for a campaign so I can verify the data.

Acceptance Criteria
---
Opening the list of ads should load ads for the appropriate campaign from the server with a GET request.

Do This
---
In `AdServerApiService.kt`, add a GET request method to `/campaigns/{campID}/ads`.
In `AdFrag.kt`, load the list of ads using this method.

Estimate: 1 hour

**Comment by SantaMariaF21** [comment]
Total time needed: 1 hour
